// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {detection} from '../models';
import {logger} from '../models';
import {evidence} from '../models';
import {git} from '../models';
import {main} from '../models';
import {config} from '../models';

export function AddBacklogItem(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function AddProject(arg1:models.Project):Promise<Array<string>>;

export function AutoAssignPorts():Promise<number>;

export function BrowseFolder():Promise<string>;

export function ClearAppLog():Promise<void>;

export function DeleteBacklogItem(arg1:number,arg2:string):Promise<void>;

export function DetectProjectConfig(arg1:string):Promise<detection.ProjectConfig>;

export function GetAppLog():Promise<Array<logger.Entry>>;

export function GetBacklog(arg1:number):Promise<Array<models.BacklogItem>>;

export function GetEvidence(arg1:number):Promise<Array<evidence.File>>;

export function GetEvidenceThumbnail(arg1:string):Promise<string>;

export function GetGitStatus(arg1:number):Promise<git.Status>;

export function GetMonitorData():Promise<main.MonitorData>;

export function GetPlaywrightStatus(arg1:number):Promise<main.PlaywrightStatus>;

export function GetProjects():Promise<Array<models.Project>>;

export function GetScriptStatus(arg1:number):Promise<main.ScriptStatus>;

export function GetScripts(arg1:number):Promise<Array<detection.Script>>;

export function GetServerStatus(arg1:number):Promise<main.ServerStatus>;

export function GetSettings():Promise<config.Settings>;

export function GitAction(arg1:number,arg2:string):Promise<void>;

export function KillTree(arg1:number):Promise<main.NotifyResult>;

export function MoveBacklogItem(arg1:number,arg2:string,arg3:number):Promise<void>;

export function OpenContainingFolder(arg1:string):Promise<void>;

export function OpenExternally(arg1:string):Promise<void>;

export function OpenHTMLReport(arg1:number):Promise<void>;

export function OpenInExplorer(arg1:number):Promise<void>;

export function OpenOpenCode(arg1:number):Promise<void>;

export function OpenTerminal(arg1:number):Promise<void>;

export function OpenTraceViewer(arg1:number,arg2:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function OpenVSCode(arg1:number):Promise<void>;

export function Quit():Promise<void>;

export function ReloadProjects():Promise<void>;

export function SaveDetectedPort(arg1:number,arg2:number):Promise<Array<string>>;

export function RemoveProject(arg1:number):Promise<void>;

export function RestartApp():Promise<void>;

export function RestartServer(arg1:number):Promise<void>;

export function RunDebug(arg1:number):Promise<void>;

export function RunScript(arg1:number,arg2:string,arg3:string):Promise<void>;

export function RunTests(arg1:number):Promise<void>;

export function RunUI(arg1:number):Promise<void>;

export function SetSetting(arg1:string,arg2:string):Promise<Array<string>>;

export function ShowReport(arg1:number):Promise<void>;

export function StartServer(arg1:number):Promise<void>;

export function StopPlaywright(arg1:number):Promise<void>;

export function StopScript(arg1:number):Promise<void>;

export function StopServer(arg1:number):Promise<void>;

export function TogglePin(arg1:number):Promise<void>;

export function UpdateBacklogItem(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function UpdateProject(arg1:number,arg2:models.Project):Promise<Array<string>>;
