// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {git} from '../models';
import {main} from '../models';
import {detection} from '../models';

export function AddProject(arg1:models.Project):Promise<Array<string>>;

export function GetGitStatus(arg1:number):Promise<git.Status>;

export function GetPlaywrightStatus(arg1:number):Promise<main.PlaywrightStatus>;

export function GetProjects():Promise<Array<models.Project>>;

export function GetScriptStatus(arg1:number):Promise<main.ScriptStatus>;

export function GetScripts(arg1:number):Promise<Array<detection.Script>>;

export function GetServerStatus(arg1:number):Promise<main.ServerStatus>;

export function GitAction(arg1:number,arg2:string):Promise<void>;

export function RemoveProject(arg1:number):Promise<void>;

export function RestartServer(arg1:number):Promise<void>;

export function RunDebug(arg1:number):Promise<void>;

export function RunScript(arg1:number,arg2:string,arg3:string):Promise<void>;

export function RunTests(arg1:number):Promise<void>;

export function RunUI(arg1:number):Promise<void>;

export function ShowReport(arg1:number):Promise<void>;

export function StartServer(arg1:number):Promise<void>;

export function StopPlaywright(arg1:number):Promise<void>;

export function StopScript(arg1:number):Promise<void>;

export function StopServer(arg1:number):Promise<void>;

export function TogglePin(arg1:number):Promise<void>;

export function UpdateProject(arg1:number,arg2:models.Project):Promise<Array<string>>;
