// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddProject(arg1:models.Project):Promise<Array<string>>;

export function GetProjects():Promise<Array<models.Project>>;

export function GetServerStatus(arg1:number):Promise<main.ServerStatus>;

export function RemoveProject(arg1:number):Promise<void>;

export function RestartServer(arg1:number):Promise<void>;

export function StartServer(arg1:number):Promise<void>;

export function StopServer(arg1:number):Promise<void>;

export function TogglePin(arg1:number):Promise<void>;

export function UpdateProject(arg1:number,arg2:models.Project):Promise<Array<string>>;
